name: Ansible Role Pull Request Validator
on:
  workflow_call:

jobs:
  ansible-pr-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Install Poetry
        run: "curl -sSL https://install.python-poetry.org | python3 -"

      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: poetry

      - name: Run Molecule test case
        uses: robertdebock/molecule-action@6.0.1
